config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index' #
  controller :sessions do
    get 'login' => :new #
    post 'login' => :create #
    delete 'logout' => :destroy #
  end

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member #
  end

  root to: 'store#index', as: 'store', via: :all #set store on the main page

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> <!-- (some) protection -->
</head>

<body class='<%= controller.controller_name %>'> <!-- add css to controller with equal name -->
  <div id="banner">
    <div class="title">
      <%= image_tag("logo.png") %>
      <%= @page_title || "Store" %>
    </div>
  </div>

  <div id="columns">
    <aside>
      <div id="cart">
        <% if @cart %> <!--help to reduce error with line_items, which is nil here-->
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %> <!--cart now rendered in sidebar-->
          <% end %>
        <% end %>
      </div>

      <ul>
        <li><%= link_to 'Home', store_path %></li>
        <li><%= link_to 'Login', admin_path %></li>
        <li><a href="https://telegram.me/hellofr1end">Contact</a></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
        </ul>

        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
    </aside>

    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>